### ISSUE TITLE
Calculadora Velocidad Fija

### ISSUE THREAD

**Issue by BASM7** [jose-andres-ucr/agro#8]
Como productor agrícola, quiero una calculadora en la aplicación que me permita ingresar los valores necesarios para calibrar mi equipo de aplicación de herbicidas, con el método de velocidad fija, de manera intuitiva y precisa, para garantizar una aplicación efectiva y segura de los productos.

## Pending TO-DO items:

- [ ] Review .toString() castings.
- [ ] Review UI stuff.
- [ ] Review amount of decimals to show. Also is Number a good choice?
- [ ] Error handling with empty fields.
- [ ] Research screen orientation.
- [ ] Consider validations for octal, hex, or other bases.

**Comment by merojosa** [comment]
Favor actualizar el estado del issue
